### ISSUE TITLE
Error is displayed

### ISSUE THREAD

**Issue by superdeen** [mhmdiaa/second-order#12]
Nice tool! Unfortunately it always return this error:

stat second-order.go: no such file or directory.
What am I doing wrongly?

**Comment by superdeen** [comment]
Note I also tried moving the tool to /bin, yet it did not work

**Comment by mhmdiaa** [comment]
Hi there,

You need to be in the folder where you cloned the repository to use the command `go run second-order.go` (the file `second-order.go` needs to be in your current working directory). If you moved the compiled binary (not the source code file) into `/bin`, you should be able to run it using just `second-order` as it will be in your `$PATH` environment variable.

Feel free to open a new issue if you run into any problems.
