### ISSUE TITLE
DOUBT

### ISSUE THREAD

**Issue by 3th1cyuk1** [mhmdiaa/second-order#13]
Hello Team,

How to include a list of targets into a file and then proceed with the tool? Are there any ways to do that?

Regards,
3th1c_yuk1

**Comment by mhmdiaa** [comment]
Hi @3th1cyuk1,

Currently, there is no built-in way to do this but you can use something like `xargs` or `parallel`.
```
xargs -I % second-order -target % < LIST_OF_TARGETS
```
