### ISSUE TITLE
Feature request: storing all the requested urls/endpoints 

### ISSUE THREAD

**Issue by ehsandeep** [mhmdiaa/second-order#3]
As second-order do crawl the request based on chain of links and hit maximums endpoints to fetch the data back, but not storing requested endpoints/url  but i can see those endpoints can be used to other purpose as well like feeding those endpoints to [InputScanner](https://github.com/zseano/InputScanner) which can find other things as well.

**Comment by mhmdiaa** [comment]
Nice idea! I will add it to my TODO list.

**Comment by ehsandeep** [comment]
Thanks :)

some points to note for this:

- Make sure target urls is shorted, as we are interested in the target endpoints more.
- In case there is other endpoint, you can ignore or store into other file or some option for that.

**Comment by mhmdiaa** [comment]
You mean I should only save endpoints not a complete URL (http://target.com/foo -> foo)? That can cause some problems as second-order also crawls subdomains, so you wouldn't know on which subdomain an endpoint was found. This can be solved if we store endpoints and subdomains (http://foo.target.com/bar -> [foo, bar]).
Not sure I understand the second point. Can you explain a bit more?

**Comment by ehsandeep** [comment]
nah, sorry not being clear where by **shorted** i mean save the target endpoints should be priorities in this the list!

let's say you have endpoints
```
aa.com/foo
bb.com/bar
cc.aa.com/bar
target.com/bar
aa.target.com/bar
bb.target.com/bar
```

then the result should be like as we are looking endpoints for the **target.com**. 

```
target.com/bar
aa.target.com/bar
bb.target.com/bar
```
other results also can be stored optional or something other list as you think.
and nah, store the full url only not just endpoint!

i hope both point is clear now?

**Comment by mhmdiaa** [comment]
Yes, everything is clear now. I'll see what I can do

**Comment by mhmdiaa** [comment]
Done. You can use the `-log` flag to instruct Second Order to log all crawled URLs to a text file.
Thanks for the suggestion!

**Comment by ehsandeep** [comment]
Hello @mhmdiaa, 

Great work, i can confirm it's working, i'm assuming it's storing unique endpoints in log file, if there is any duplicate in it.

**Comment by mhmdiaa** [comment]
Hi @madaratech,

Yes, It stores visited endpoints only, and since it only visits each URL once, even if it shows up in another page, all URLs there will be unique.

Thanks for confirming
