### ISSUE TITLE
Export collected data to the results file once it reaches a specific limit to reduce memory usage

### ISSUE THREAD

**Issue by mhmdiaa** [mhmdiaa/second-order#8]
When the collected data has reached a specific limit, dump it to a file and free its memory. This way, we can save a lot of memory, and update the results file periodically, so if the tool crashes, or is forced to exit, the user will have the already gathered data.

**Comment by sumgr0** [comment]
Hi mhmdiaa,

I was trying the tool on a target(s) and noticed that the command line kills the process after a while. 

Is this the same issue noted here?

**Comment by mhmdiaa** [comment]
Hi @sumgr0,

Sorry I completely missed your comment. Yeah, this could be it; the old implementation had some performance issues that were fixed in the new release.

Try it out and let me know if you run into any problems!
