### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hussam-dh** [mhmdiaa/second-order#9]
Salam Muhammed,
I got this error while trying to install second order:
go/src/github.com/mhmdiaa/second-order/second-order.go:292: linkurl.Hostname undefined (type *url.URL has no field or method Hostname)

any Suggeestions?
Thanks

**Comment by hussam-dh** [comment]
actually to be clear this what i got when running got get:
# github.com/mhmdiaa/second-order
go/src/github.com/mhmdiaa/second-order/second-order.go:292: linkurl.Hostname undefined (type *url.URL has no field or method Hostname)
go/src/github.com/mhmdiaa/second-order/second-order.go:295: baseURL.Hostname undefined (type *url.URL has no field or method Hostname)

Thanks

**Comment by mhmdiaa** [comment]
Salam Hussam,

You need to update your Go version to >= 1.8. You can use `go version` to check the version you have.

**Comment by hussam-dh** [comment]
Thanks A lot Muhammed
